#!name=VVEBO Fix
#!desc=VVEBO 用户时间线及粉丝列表修复 - Quantumult X
#!author=Tizzy-3

[rewrite_local]

# 保存 UID
^https:\/\/api\.weibo\.cn\/2\/remind\/unread_count\? url script-request-header https://raw.githubusercontent.com/Tizzy-3/quantumultX/refs/heads/main/fix-vvebo-user-timeline-qx.js

# 修复用户主页时间线请求
^https:\/\/api\.weibo\.cn\/2\/statuses\/user_timeline\? url script-request-header https://raw.githubusercontent.com/Tizzy-3/quantumultX/refs/heads/main/fix-vvebo-user-timeline-qx.js

# 转换用户主页时间线响应
^https:\/\/api\.weibo\.cn\/2\/profile\/statuses\/tab\? url script-response-body https://raw.githubusercontent.com/Tizzy-3/quantumultX/refs/heads/main/fix-vvebo-user-timeline-qx.js

# 修复粉丝列表
^https:\/\/api\.weibo\.cn\/2\/cardlist\?.*selffans url script-response-body https://raw.githubusercontent.com/Tizzy-3/quantumultX/refs/heads/main/fix-vvebo-fans-qx.js

[mitm]

hostname = api.weibo.cn
